<?php
$config = array (
  'debug' => 0,
  'MISP' => 
  array (
    'baseurl' => 'http://192.168.0.14',
    'footermidleft' => 'This is an initial install',
    'footermidright' => 'Please configure and harden accordingly',
    'org' => 'ORGNAME',
    'showorg' => true,
    'threatlevel_in_email_subject' => true,
    'email_subject_TLP_string' => 'tlp:amber',
    'email_subject_tag' => 'tlp',
    'email_subject_include_tag_name' => true,
    'background_jobs' => true,
    'osuser' => 'www-data',
    'email' => 'info@admin.test',
    'contact' => 'info@admin.test',
    'cveurl' => 'https://vulnerability.circl.lu/vuln/',
    'cweurl' => 'https://vulnerability.circl.lu/cwes/',
    'disablerestalert' => true,
    'default_event_distribution' => '1',
    'default_attribute_distribution' => 'event',
    'tagging' => true,
    'full_tags_on_event_index' => true,
    'attribute_tagging' => true,
    'full_tags_on_attribute_index' => true,
    'footer_logo' => '',
    'take_ownership_xml_import' => false,
    'unpublishedprivate' => false,
    'disable_emailing' => true,
    'manage_workers' => true,
    'python_bin' => '/var/www/MISP/venv/bin/python',
    'external_baseurl' => '',
    'forceHTTPSforPreLoginRequestedURL' => false,
    'showCorrelationsOnIndex' => true,
    'default_event_tag_collection' => 0,
    'language' => 'eng',
    'proposals_block_attributes' => false,
    'redis_host' => '127.0.0.1',
    'redis_port' => 6379,
    'redis_database' => 13,
    'redis_password' => '',
    'ssdeep_correlation_threshold' => 40,
    'extended_alert_subject' => false,
    'default_event_threat_level' => '4',
    'newUserText' => 'Dear new MISP user,\\n\\nWe would hereby like to welcome you to the $org MISP community.\\n\\n Use the credentials below to log into MISP at $misp, where you will be prompted to manually change your password to something of your own choice.\\n\\nUsername: $username\\nPassword: $password\\n\\nIf you have any questions, don\'t hesitate to contact us at: $contact.\\n\\nBest regards,\\nYour $org MISP support team',
    'passwordResetText' => 'Dear MISP user,\\n\\nA password reset has been triggered for your account. Use the below provided temporary password to log into MISP at $misp, where you will be prompted to manually change your password to something of your own choice.\\n\\nUsername: $username\\nYour temporary password: $password\\n\\nIf you have any questions, don\'t hesitate to contact us at: $contact.\\n\\nBest regards,\\nYour $org MISP support team',
    'enableEventBlocklisting' => true,
    'enableOrgBlocklisting' => true,
    'log_client_ip' => true,
    'log_auth' => false,
    'store_api_access_time' => false,
    'disableUserSelfManagement' => false,
    'disable_user_login_change' => false,
    'disable_user_password_change' => false,
    'disable_user_add' => false,
    'block_event_alert' => false,
    'block_event_alert_tag' => 'no-alerts="true"',
    'block_old_event_alert' => false,
    'block_old_event_alert_age' => 0,
    'block_old_event_alert_by_date' => 0,
    'incoming_tags_disabled_by_default' => false,
    'maintenance_message' => 'Great things are happening! MISP is undergoing maintenance, but will return shortly. You can contact the administration at $email.',
    'welcome_text_top' => 'Initial Install, please configure',
    'welcome_text_bottom' => 'Welcome to MISP on ubuntu, change this message in MISP Settings',
    'attachments_dir' => '/var/www/MISP/app/files',
    'download_attachments_on_load' => true,
    'title_text' => 'MISP',
    'terms_download' => false,
    'showorgalternate' => false,
    'event_view_filter_fields' => 'id, uuid, value, comment, type, category, Tag.name',
    'live' => true,
    'uuid' => 'eb20ce5e-4d7f-40d7-a201-b26dfdf59f4f',
    'delegation' => true,
    'max_correlations_per_event' => 5000,
    'disable_auto_logout' => false,
    'log_paranoid_skip_db' => false,
    'log_paranoid' => false,
    'log_user_ips' => true,
    'event_alert_republish_ban' => false,
    'event_alert_republish_ban_threshold' => 5,
    'event_alert_republish_ban_refresh_on_retry' => false,
    'user_email_notification_ban' => true,
    'user_email_notification_ban_time_threshold' => 120,
    'user_email_notification_ban_amount_threshold' => 10,
    'user_email_notification_ban_refresh_on_retry' => true,
    'warning_for_all' => false,
    'enable_synchronisation_filtering_on_type' => false,
    'tmpdir' => '/var/www/MISP/app/tmp',
    'host_org_id' => 1,
    'log_user_ips_authkeys' => true,
    'event_alert_metadata_only' => false,
  ),
  'GnuPG' => 
  array (
    'onlyencrypted' => false,
    'email' => 'admin@admin.test',
    'homedir' => '/var/www/MISP/.gnupg',
    'password' => '55ec98d1a354808a644d5337f03eaa033b299088753ca78d560e29db0bae4535',
    'bodyonlyencrypted' => false,
    'sign' => true,
    'obscure_subject' => true,
    'binary' => '/usr/bin/gpg',
    'key_fetching_disabled' => false,
  ),
  'SMIME' => 
  array (
    'enabled' => false,
    'email' => '',
    'cert_public_sign' => '',
    'key_sign' => '',
    'password' => '',
  ),
  'Proxy' => 
  array (
    'host' => '',
    'port' => '',
    'method' => '',
    'user' => '',
    'password' => '',
  ),
  'SecureAuth' => 
  array (
    'amount' => 5,
    'expire' => 300,
  ),
  'Security' => 
  array (
    'level' => 'medium',
    'salt' => 'O-*_Tvy>w5=kFmCfEatogrjsiWNZ(jWG',
    'cipherSeed' => '',
    'require_password_confirmation' => true,
    'auth_enforced' => false,
    'rest_client_baseurl' => '',
    'advanced_authkeys' => true,
    'password_policy_length' => 12,
    'password_policy_complexity' => '/^((?=.*\\d)|(?=.*\\W+))(?![\\n])(?=.*[A-Z])(?=.*[a-z]).*$|.{16,}/',
    'self_registration_message' => 'If you would like to send us a registration request, please fill out the form below. Make sure you fill out as much information as possible in order to ease the task of the administrators.',
    'allow_self_registration' => false,
    'rest_client_enable_arbitrary_urls' => false,
    'user_monitoring_enabled' => false,
    'authkey_keep_session' => false,
    'disable_local_feed_access' => false,
    'enable_svg_logos' => false,
    'log_each_individual_auth_fail' => false,
    'disable_browser_cache' => true,
    'check_sec_fetch_site_header' => true,
    'csp_enforce' => true,
    'do_not_log_authkeys' => true,
    'username_in_response_header' => true,
  ),
  'Session' => 
  array (
    'autoRegenerate' => false,
    'timeout' => 600,
    'cookieTimeout' => 3600,
  ),
  'Plugin' => 
  array (
    'Cortex_services_enable' => false,
    'Cortex_services_url' => 'http://127.0.0.1',
    'Cortex_services_port' => 9000,
    'Cortex_timeout' => 120,
    'Cortex_authkey' => 'false',
    'Cortex_ssl_verify_peer' => false,
    'Cortex_ssl_verify_host' => false,
    'Cortex_ssl_allow_self_signed' => true,
    'Sightings_policy' => 0,
    'Sightings_anonymise' => false,
    'Sightings_anonymise_as' => 1,
    'Sightings_range' => 365,
    'Sightings_sighting_db_enable' => false,
    'ElasticSearch_logging_enable' => false,
    'S3_enable' => false,
    'CustomAuth_disable_logout' => false,
    'RPZ_walled_garden' => '127.0.0.1',
    'RPZ_serial' => '$date00',
    'RPZ_refresh' => '2h',
    'RPZ_retry' => '30m',
    'RPZ_expiry' => '30d',
    'RPZ_minimum_ttl' => '1h',
    'RPZ_ttl' => '1w',
    'RPZ_ns' => 'localhost.',
    'RPZ_ns_alt' => 'false',
    'RPZ_email' => 'root.localhost',
    'Kafka_enable' => false,
    'Kafka_brokers' => 'kafka:9092',
    'Kafka_rdkafka_config' => '/etc/rdkafka.ini',
    'Kafka_include_attachments' => false,
    'Kafka_event_notifications_enable' => false,
    'Kafka_event_notifications_topic' => 'misp_event',
    'Kafka_event_publish_notifications_enable' => false,
    'Kafka_event_publish_notifications_topic' => 'misp_event_publish',
    'Kafka_object_notifications_enable' => false,
    'Kafka_object_notifications_topic' => 'misp_object',
    'Kafka_object_reference_notifications_enable' => false,
    'Kafka_object_reference_notifications_topic' => 'misp_object_reference',
    'Kafka_attribute_notifications_enable' => false,
    'Kafka_attribute_notifications_topic' => 'misp_attribute',
    'Kafka_shadow_attribute_notifications_enable' => false,
    'Kafka_shadow_attribute_notifications_topic' => 'misp_shadow_attribute',
    'Kafka_tag_notifications_enable' => false,
    'Kafka_tag_notifications_topic' => 'misp_tag',
    'Kafka_sighting_notifications_enable' => false,
    'Kafka_sighting_notifications_topic' => 'misp_sighting',
    'Kafka_user_notifications_enable' => false,
    'Kafka_user_notifications_topic' => 'misp_user',
    'Kafka_organisation_notifications_enable' => false,
    'Kafka_organisation_notifications_topic' => 'misp_organisation',
    'Kafka_audit_notifications_enable' => false,
    'Kafka_audit_notifications_topic' => 'misp_audit',
    'ZeroMQ_enable' => false,
    'ZeroMQ_host' => '127.0.0.1',
    'ZeroMQ_port' => 50000,
    'ZeroMQ_redis_host' => 'localhost',
    'ZeroMQ_redis_port' => 6379,
    'ZeroMQ_redis_database' => '1',
    'ZeroMQ_redis_namespace' => 'mispq',
    'ZeroMQ_event_notifications_enable' => false,
    'ZeroMQ_object_notifications_enable' => false,
    'ZeroMQ_object_reference_notifications_enable' => false,
    'ZeroMQ_attribute_notifications_enable' => false,
    'ZeroMQ_sighting_notifications_enable' => false,
    'ZeroMQ_user_notifications_enable' => false,
    'ZeroMQ_organisation_notifications_enable' => false,
    'ZeroMQ_include_attachments' => false,
    'ZeroMQ_tag_notifications_enable' => false,
  ),
  'SimpleBackgroundJobs' => 
  array (
    'enabled' => false,
    'redis_host' => 'localhost',
    'redis_port' => 6379,
    'redis_password' => '',
    'redis_database' => 1,
    'redis_namespace' => 'background_jobs',
    'max_job_history_ttl' => 86400,
    'supervisor_host' => 'localhost',
    'supervisor_port' => 9001,
    'supervisor_user' => 'supervisor',
    'supervisor_password' => '',
  ),
  'LinOTPAuth' => 
  array (
    'enabled' => false,
    'baseUrl' => 'https://<your-linotp-baseUrl>',
    'realm' => 'lino',
    'verifyssl' => true,
    'mixedauth' => false,
  ),
);
